# Generated by Django 4.2 on 2023-10-12 19:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_web', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='primerlapso',
            name='Observacion',
            field=models.TextField(blank=True),
        ),
    ]
