# Generated by Django 4.2 on 2023-10-12 19:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_web', '0002_primerlapso_observacion'),
    ]

    operations = [
        migrations.AddField(
            model_name='segundolapso',
            name='Observacion',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='tercerlapso',
            name='Observacion',
            field=models.TextField(blank=True),
        ),
    ]
