# Generated by Django 4.2 on 2023-10-12 19:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_web', '0003_segundolapso_observacion_tercerlapso_observacion'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='primerlapso',
            name='Observacion',
        ),
        migrations.RemoveField(
            model_name='segundolapso',
            name='Observacion',
        ),
        migrations.RemoveField(
            model_name='tercerlapso',
            name='Observacion',
        ),
    ]
