# Generated by Django 4.2 on 2023-10-13 18:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_web', '0008_authuser_estudiante_fecha_de_nac_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='estudiante',
            name='Fecha_de_nac',
            field=models.DateField(blank=True, null=True),
        ),
    ]
