# Generated by Django 4.2 on 2023-10-13 18:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_web', '0009_alter_estudiante_fecha_de_nac'),
    ]

    operations = [
        migrations.AlterField(
            model_name='estudiante',
            name='promedio',
            field=models.CharField(blank=True, max_length=5),
        ),
    ]
