# Generated by Django 4.2 on 2023-10-13 20:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_web', '0011_rename_fecha_de_nac_estudiante_fecha_de_nac'),
    ]

    operations = [
        migrations.AlterField(
            model_name='estudiante',
            name='fecha_de_nac',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
