# Generated by Django 4.2 on 2023-11-07 03:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('app_web', '0012_alter_estudiante_fecha_de_nac'),
    ]

    operations = [
        migrations.CreateModel(
            name='Materias_año',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('año', models.CharField(max_length=100)),
                ('materia', models.CharField(max_length=100)),
                ('codigo_asig', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_web.asignaturas')),
                ('codigo_año', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_web.aoescolar')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
