# Generated by Django 4.2 on 2023-11-08 04:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_web', '0013_materias_año'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contenido_materia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_materia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_web.materias_año')),
            ],
        ),
    ]
