# Generated by Django 4.2 on 2023-11-08 06:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_web', '0014_contenido_materia'),
    ]

    operations = [
        migrations.AddField(
            model_name='contenido_materia',
            name='archivos',
            field=models.FileField(null=True, upload_to='Uploaded Files/'),
        ),
        migrations.AddField(
            model_name='contenido_materia',
            name='descripcion',
            field=models.TextField(blank=True, null=True),
        ),
    ]
