# Generated by Django 4.2 on 2023-11-08 17:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_web', '0015_contenido_materia_archivos_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contenido_materia',
            name='archivos',
        ),
    ]
