# Generated by Django 4.2 on 2023-11-08 17:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_web', '0016_remove_contenido_materia_archivos'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contenido_materia',
            name='id_materia',
        ),
    ]
