# Generated by Django 4.2 on 2023-11-08 18:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_web', '0017_remove_contenido_materia_id_materia'),
    ]

    operations = [
        migrations.AddField(
            model_name='contenido_materia',
            name='id_materia',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app_web.asignaturas'),
        ),
    ]
