# Generated by Django 4.2 on 2023-11-08 19:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_web', '0018_contenido_materia_id_materia'),
    ]

    operations = [
        migrations.AddField(
            model_name='materias_año',
            name='descripcion',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='contenido_materia',
            name='id_materia',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app_web.materias_año'),
        ),
    ]
