# Generated by Django 4.2 on 2023-11-08 21:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('app_web', '0019_materias_año_descripcion_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contenido_materia',
            name='id_materia',
        ),
        migrations.AddField(
            model_name='contenido_materia',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
