# Generated by Django 4.2 on 2023-11-09 00:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('app_web', '0020_remove_contenido_materia_id_materia_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='contenido_materia',
            name='id_materia',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app_web.materias_año'),
        ),
        migrations.AlterField(
            model_name='contenido_materia',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
