# Generated by Django 4.2 on 2023-11-09 00:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_web', '0021_contenido_materia_id_materia_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='contenido_materia',
            name='titulo',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
