# Generated by Django 4.2 on 2023-11-09 21:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('app_web', '0022_contenido_materia_titulo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='eaoesc',
            name='dni',
        ),
        migrations.AddField(
            model_name='eaoesc',
            name='userr',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
