# Generated by Django 4.2 on 2023-11-11 01:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_web', '0023_remove_eaoesc_dni_eaoesc_userr'),
    ]

    operations = [
        migrations.AddField(
            model_name='contenido_materia',
            name='archivos',
            field=models.FileField(null=True, upload_to='Uploaded_Files/'),
        ),
    ]
