# Generated by Django 4.2 on 2023-11-15 06:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_web', '0024_contenido_materia_archivos'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contenido_materia',
            name='archivos',
            field=models.FileField(null=True, upload_to=''),
        ),
    ]
