# Generated by Django 4.2 on 2023-11-15 07:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_web', '0025_alter_contenido_materia_archivos'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='materias_año',
            name='descripcion',
        ),
    ]
