# Generated by Django 4.2 on 2023-11-15 08:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_web', '0026_remove_materias_año_descripcion'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='primerlapso',
            name='user',
        ),
    ]
