# Generated by Django 4.2 on 2023-11-15 08:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_web', '0028_remove_primerlapso_dni_primerlapso_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='primerlapso',
            name='dni',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app_web.estudiante'),
        ),
    ]
