# Generated by Django 4.2 on 2023-11-17 18:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_web', '0029_primerlapso_dni'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='authuser',
            options={},
        ),
    ]
