# Generated by Django 4.2 on 2023-11-17 18:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_web', '0031_authuser_docent_authuser_roles_alter_authuser_table'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='authuser',
            options={'managed': False},
        ),
    ]
