# Generated by Django 4.2 on 2023-11-17 18:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_web', '0035_remove_authuser_docent_remove_authuser_roles_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='authuser',
            options={'managed': False},
        ),
    ]
