# Generated by Django 4.2 on 2023-11-17 18:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_web', '0049_alter_authuser_options'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='authuser',
            table='auth_user',
        ),
    ]
