# Generated by Django 4.2 on 2023-11-17 19:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_web', '0055_alter_authuser_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='authuser',
            name='docent',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterModelTable(
            name='authuser',
            table=None,
        ),
    ]
