# Generated by Django 4.2 on 2023-11-17 21:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_web', '0060_alter_docent_user'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='authuser',
            options={},
        ),
    ]
