# Generated by Django 4.2 on 2023-11-17 23:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_web', '0064_alter_authuser_table'),
    ]

    operations = [
        migrations.RenameField(
            model_name='docent',
            old_name='user',
            new_name='user_id',
        ),
        migrations.AddField(
            model_name='docent',
            name='name',
            field=models.CharField(max_length=25, null=True),
        ),
    ]
