# Generated by Django 4.2 on 2023-11-18 01:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_web', '0065_rename_user_docent_user_id_docent_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='docent',
            old_name='name',
            new_name='user_name',
        ),
        migrations.RenameField(
            model_name='estudiante',
            old_name='userr',
            new_name='user_id',
        ),
        migrations.AddField(
            model_name='estudiante',
            name='user_name',
            field=models.CharField(max_length=25, null=True),
        ),
    ]
