# Generated by Django 4.2 on 2023-11-18 01:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_web', '0066_rename_name_docent_user_name_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='estudiante',
            old_name='user_id',
            new_name='userr',
        ),
        migrations.RemoveField(
            model_name='docent',
            name='user_name',
        ),
        migrations.RemoveField(
            model_name='estudiante',
            name='user_name',
        ),
        migrations.AddField(
            model_name='docent',
            name='name',
            field=models.CharField(max_length=60, null=True),
        ),
    ]
