# Generated by Django 4.2 on 2023-11-18 21:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_web', '0067_rename_user_id_estudiante_userr_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='authuser',
            options={},
        ),
    ]
