# Generated by Django 4.2 on 2023-11-18 21:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_web', '0068_alter_authuser_options'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='authuser',
            table=None,
        ),
    ]
